version: "3.9"
services:
  # app services
  postgres:
    image: "arm64v8/postgres:15.3-alpine"
    restart: always
    env_file:
      - "./config/postgres/.env.docker-compose"
    volumes:
      - "aha_pg_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  backend:
    build:
      context: .
      dockerfile: "./dockerfiles/Dockerfile"
    command: "npx nx run backend:serve:development"
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    env_file:
      - "./packages/backend/.env.docker-compose"
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
      - db_setup
  frontend:
    build:
      context: .
      dockerfile: "./dockerfiles/Dockerfile"
    command: "npx nx run frontend:serve:development"
    ports:
      - "4200:4200"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    env_file:
      - "./packages/frontend/.env.docker-compose"
    environment:
      - VITE_PROXY_HOST=backend
    depends_on:
      - backend
    tty: true
  db_setup:
    build:
      context: .
      dockerfile: "./dockerfiles/Dockerfile"
    working_dir: /app
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    depends_on:
      - postgres
    env_file:
      - "packages/prisma/prisma/.env.docker-compose"
    command: "npx prisma db push --schema=packages/prisma/prisma/schema.prisma"
  # utility services
  npm:
    build:
      context: .
      dockerfile: "./dockerfiles/Dockerfile"
    working_dir: /app
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    entrypoint: npm
  prisma:
    build:
      context: .
      dockerfile: "./dockerfiles/Dockerfile"
    working_dir: /app
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    env_file:
      - "packages/prisma/prisma/.env.docker-compose"
    entrypoint: ["npx", "prisma"]
  nx:
    build:
      context: .
      dockerfile: "./dockerfiles/Dockerfile"
    working_dir: /app
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    entrypoint: ["npx", "nx"]
volumes:
  aha_pg_data:
  node_modules:
