apiVersion: v1
kind: Secret
metadata:
  name: backend-sc
type: Opaque
data:
  AUTH0_AUTH_DOMAIN: fool
  AUTH0_AUTH_CLIENT_ID: fool
  AUTH0_AUTH_AUDIENCE: fool
  AUTH0_MANAGEMENT_DOMAIN: fool
  AUTH0_MANAGEMENT_CLIENT_ID: fool
  AUTH0_MANAGEMENT_CLIENT_SECRET: fool
  AUTH0_MANAGEMENT_AUDIENCE: fool
  APP_JWT_SECRET_KEY: fool
  SENDGRID_API_KEY: fool
