# Use secrets for things which are actually secret like API keys, credentials, etc
# Base64 encode the values stored in a Kubernetes Secret: $ pbpaste | base64 | pbcopy
# The --decode flag is convenient: $ pbpaste | base64 --decode
apiVersion: v1
kind: Secret
metadata:
  name: postgres-sc
type: Opaque
data:
  POSTGRES_USER: fool # enter your value
  POSTGRES_PASSWORD: fool # enter your value
  POSTGRES_DB: fool # enter your value
