apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /var/lib/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
  volumeName: postgres-pv
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-sv
spec:
  selector:
    app: postgres
  # type: ClusterIP
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-ss
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres-sv
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "postgres:15.2-alpine"
          ports:
            - containerPort: 5432
              name: postgres
              protocol: TCP
          envFrom:
            - secretRef:
                name: postgres-sc
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: "postgres-pvc"
      volumes:
        - name: "postgres-pvc"
          persistentVolumeClaim:
            claimName: postgres-pvc
